language: scala
scala:
   - 2.11.6
env:
- PLAY_VERSION=2.0.2

before_script:
- wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script:
- sbt test
